import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export type Point=number[];
export type MapData={roads:{name:string;points:Point[]}[];route:Point[];buildings:{points:Point[];height:number}[];coast?:Point[][];parks?:Point[][]};
export type HUD={mode:string;speed:number;time:number;boost:number;progress:number;street:string;position:number;count:number;drift:boolean;camera:string};
const distance=(a:Point,b:Point)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
export function makeGame(canvas:HTMLCanvasElement,mini:HTMLCanvasElement,d:MapData,update:(h:HUD)=>void){
const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.6));renderer.setClearColor('#8dd5ed');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene();scene.fog=new T.Fog('#b3deec',180,680);const camera=new T.PerspectiveCamera(65,1,.15,1300);scene.add(new T.HemisphereLight('#e5f9ff','#827f5b',2.5));const sun=new T.DirectionalLight('#fff1c6',3.1);sun.position.set(-160,240,-80);scene.add(sun);
const material=(color:T.ColorRepresentation)=>new T.MeshStandardMaterial({color,roughness:.85});const ground=new T.Mesh(new T.PlaneGeometry(6500,6500),material('#c5cbb7'));ground.rotation.x=-Math.PI/2;ground.position.y=-.2;scene.add(ground);
const boxGeo=new T.BoxGeometry(1,1,1);const cube=(parent:T.Object3D,x:number,y:number,z:number,sx:number,sy:number,sz:number,color:T.ColorRepresentation)=>{const m=new T.Mesh(boxGeo,material(color));m.position.set(x,y,z);m.scale.set(sx,sy,sz);parent.add(m);return m;};
function ribbons(lines:Point[][],width:number,color:string,y:number){const vertices:number[]=[];for(const points of lines)for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],len=distance(a,b);if(!len)continue;const nx=-(b[1]-a[1])/len*width/2,nz=(b[0]-a[0])/len*width/2;vertices.push(a[0]+nx,y,a[1]+nz,b[0]+nx,y,b[1]+nz,a[0]-nx,y,a[1]-nz,b[0]+nx,y,b[1]+nz,b[0]-nx,y,b[1]-nz,a[0]-nx,y,a[1]-nz);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));geo.computeVertexNormals();const mat=material(color);mat.side=T.DoubleSide;const mesh=new T.Mesh(geo,mat);scene.add(mesh);return mesh;}
ribbons(d.roads.map(r=>r.points),22,'#e1ddcd',.015);ribbons(d.roads.map(r=>r.points),17,'#586877',.055);ribbons([d.route],.6,'#91ffcd',.09);
// Road markings are aligned with the downloaded centerlines.
const stripes:T.Matrix4[]=[];const temp=new T.Object3D();for(const road of d.roads){for(let i=1;i<road.points.length;i++){const a=road.points[i-1],b=road.points[i],len=distance(a,b);for(let t=4;t<len;t+=15){temp.position.set(a[0]+(b[0]-a[0])*t/len,.08,a[1]+(b[1]-a[1])*t/len);temp.rotation.set(0,-Math.atan2(b[1]-a[1],b[0]-a[0]),0);temp.scale.set(Math.min(4,len-t),.015,.17);temp.updateMatrix();stripes.push(temp.matrix.clone());}}}const stripeMesh=new T.InstancedMesh(boxGeo,material('#f8eab7'),stripes.length);stripes.forEach((m,i)=>stripeMesh.setMatrixAt(i,m));scene.add(stripeMesh);
// Actual OSM footprints, with stylized facade colors and estimated heights where absent.
const colors=['#e1a47e','#8cb9b6','#b8c4d6','#e4c989','#c8afc4','#d8d9ce'];const groups:T.BufferGeometry[][]=colors.map(()=>[]);const windows:T.Matrix4[]=[];
d.buildings.forEach((b,index)=>{if(b.points.length<4)return;const shape=new T.Shape();b.points.forEach((p,i)=>i?shape.lineTo(p[0],-p[1]):shape.moveTo(p[0],-p[1]));const geo=new T.ExtrudeGeometry(shape,{depth:b.height,bevelEnabled:false,steps:1});geo.rotateX(-Math.PI/2);groups[index%colors.length].push(geo);for(let i=1;i<b.points.length&&windows.length<23000;i++){const a=b.points[i-1],p=b.points[i],len=distance(a,p);if(len<5||len>160)continue;const ang=Math.atan2(p[1]-a[1],p[0]-a[0]);for(let along=3;along<len-2;along+=5)for(let y=3;y<Math.min(b.height-1,55);y+=4.5){temp.position.set(a[0]+Math.cos(ang)*along+Math.sin(ang)*.06,y,a[1]+Math.sin(ang)*along-Math.cos(ang)*.06);temp.rotation.set(0,-ang,0);temp.scale.set(1.7,2,.15);temp.updateMatrix();windows.push(temp.matrix.clone());}}});
groups.forEach((list,i)=>{if(!list.length)return;const merged=mergeGeometries(list);scene.add(new T.Mesh(merged,material(colors[i])));list.forEach(g=>g.dispose());});const wm=new T.InstancedMesh(boxGeo,material('#365c73'),windows.length);windows.forEach((m,i)=>wm.setMatrixAt(i,m));scene.add(wm);
if(d.coast?.length){for(const coast of d.coast){ribbons([coast],3,'#ddd1b0',.1);const waterShape=new T.Shape();const pts=[...coast,[3000,coast[coast.length-1][1]],[3000,coast[0][1]]];pts.forEach((p,i)=>i?waterShape.lineTo(p[0],-p[1]):waterShape.moveTo(p[0],-p[1]));const water=new T.Mesh(new T.ShapeGeometry(waterShape),new T.MeshStandardMaterial({color:'#32a8c4',roughness:.3,metalness:.25,side:T.DoubleSide}));water.rotation.x=-Math.PI/2;water.position.y=-.12;scene.add(water);}}
for(const park of d.parks||[]){const shape=new T.Shape();park.forEach((p,i)=>i?shape.lineTo(p[0],-p[1]):shape.moveTo(p[0],-p[1]));const m=new T.Mesh(new T.ShapeGeometry(shape),material('#76b955'));m.rotation.x=-Math.PI/2;m.position.y=.12;scene.add(m);}
const lengths=[0];for(let i=1;i<d.route.length;i++)lengths.push(lengths[i-1]+distance(d.route[i-1],d.route[i]));const total=lengths[lengths.length-1];function at(s:number){s=Math.max(0,Math.min(total-.01,s));let i=1;while(lengths[i]<s)i++;const a=d.route[i-1],b=d.route[i],t=(s-lengths[i-1])/(lengths[i]-lengths[i-1]||1);return {x:a[0]+(b[0]-a[0])*t,z:a[1]+(b[1]-a[1])*t,a:Math.atan2(b[1]-a[1],b[0]-a[0])};}
const checks:number[]=[];for(let s=60;s<total-25;s+=60)checks.push(s);checks.push(total);
function kart(color:string){const group=new T.Group();cube(group,0,.55,0,3.4,.55,1.65,color);cube(group,1.15,.9,0,1,.4,1.45,color);cube(group,-.85,.95,0,.35,1.1,1.2,'#263544');cube(group,-1.5,1.2,0,.3,.15,2.3,color);for(const x of [-1,1])for(const z of [-1,1]){const wheel=new T.Mesh(new T.CylinderGeometry(.48,.48,.4,12),material('#202a36'));wheel.rotation.x=Math.PI/2;wheel.position.set(x,.48,z);group.add(wheel);const hub=new T.Mesh(new T.CylinderGeometry(.24,.24,.43,12),material('#e2e4db'));hub.rotation.x=Math.PI/2;hub.position.copy(wheel.position);group.add(hub);}const body=new T.Mesh(new T.CapsuleGeometry(.35,.4,4,8),material(color));body.position.set(-.3,1.35,0);group.add(body);const helmet=new T.Mesh(new T.SphereGeometry(.48,16,12),material('#fff2d2'));helmet.position.set(-.22,1.98,0);group.add(helmet);cube(group,.18,1.99,0,.12,.23,.65,'#263d56');const shadow=new T.Mesh(new T.CircleGeometry(2.2,20),new T.MeshBasicMaterial({color:'#243340',transparent:true,opacity:.2,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.1;group.add(shadow);scene.add(group);return group;}
const player=kart('#ff643b');const rivals=['#a47cff','#ffcf41','#36cad0'].map((c,i)=>({mesh:kart(c),s:12+i*8,speed:25+i*1.2}));
const ring=new T.Mesh(new T.TorusGeometry(6,.18,8,36),new T.MeshBasicMaterial({color:'#baff55',transparent:true,opacity:.8}));scene.add(ring);
const pads:T.Mesh[]=[];for(let s=160;s<total;s+=290){const p=at(s);const m=cube(scene,p.x,.13,p.z,8,.12,5,'#2de5dd');m.rotation.y=-p.a;pads.push(m);}
const trees=new T.Group();scene.add(trees);const trunkGeo=new T.CylinderGeometry(.25,.4,3,6),leafGeo=new T.IcosahedronGeometry(2.6,0),trunkMat=material('#9e785b'),leafMat=material('#54a367');for(let s=25;s<total;s+=45){const p=at(s);const side=Math.floor(s)%2?1:-1;const x=p.x-Math.sin(p.a)*12*side,z=p.z+Math.cos(p.a)*12*side;const trunk=new T.Mesh(trunkGeo,trunkMat);trunk.position.set(x,1.5,z);trees.add(trunk);const leaf=new T.Mesh(leafGeo,leafMat);leaf.position.set(x,4.2,z);trees.add(leaf);}
let mode='ready',x=d.route[0][0],z=d.route[0][1],angle=at(0).a,speed=0,time=0,boost=100,cp=0,count=3,driftCharge=0,drifting=false,boostTimer=0,progress=0,street='South Park',firstPerson=false,padCooldown=0;const keys:Record<string,boolean>={};let raf=0,last=0,hudTime=0,disposed=false;const camPos=new T.Vector3(),look=new T.Vector3();
const setKey=(key:string,value:boolean)=>{keys[key]=value;};const reset=()=>{mode='countdown';x=d.route[0][0];z=d.route[0][1];angle=at(0).a;speed=0;time=0;boost=100;cp=0;count=3;progress=0;boostTimer=0;driftCharge=0;Object.keys(keys).forEach(k=>delete keys[k]);rivals.forEach((r,i)=>r.s=12+i*8);};const pause=()=>{if(mode==='racing'||mode==='countdown')mode='paused';else if(mode==='paused')mode=count>0?'countdown':'racing';};const recover=()=>{const p=at(Math.max(0,checks[Math.max(0,cp-1)]-30));x=p.x;z=p.z;angle=p.a;speed=0;};const toggleCamera=()=>{firstPerson=!firstPerson;};
function nearest(px:number,pz:number){let best=Infinity,nx=px,nz=pz,name='';for(const r of d.roads)for(let i=1;i<r.points.length;i++){const a=r.points[i-1],b=r.points[i];if(Math.min(a[0],b[0])-20>px||Math.max(a[0],b[0])+20<px||Math.min(a[1],b[1])-20>pz||Math.max(a[1],b[1])+20<pz)continue;const dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((px-a[0])*dx+(pz-a[1])*dz)/(dx*dx+dz*dz||1))),qx=a[0]+dx*t,qz=a[1]+dz*t,dd=Math.hypot(px-qx,pz-qz);if(dd<best){best=dd;nx=qx;nz=qz;name=r.name;}}return {best,x:nx,z:nz,name};}
const handleDown=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Shift'].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true;if(e.repeat)return;if(e.key==='Escape')pause();if(e.key.toLowerCase()==='r')recover();if(e.key.toLowerCase()==='v')toggleCamera();};const handleUp=(e:KeyboardEvent)=>{keys[e.key.toLowerCase()]=false;};const blur=()=>{Object.keys(keys).forEach(k=>delete keys[k]);if(mode==='racing'||mode==='countdown')mode='paused';};window.addEventListener('keydown',handleDown);window.addEventListener('keyup',handleUp);window.addEventListener('blur',blur);
function miniMap(){const c=mini.getContext('2d');if(!c)return;const w=mini.width,h=mini.height;c.clearRect(0,0,w,h);c.fillStyle='#15374c';c.fillRect(0,0,w,h);const scale=.071;c.save();c.translate(48,102);c.scale(scale,scale);for(const r of d.roads){c.beginPath();r.points.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.strokeStyle='#54798a';c.lineWidth=8;c.stroke();}c.beginPath();d.route.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.strokeStyle='#baff55';c.lineWidth=27;c.stroke();for(const r of rivals){const p=at(r.s);c.fillStyle='#fff';c.beginPath();c.arc(p.x,p.z,35,0,7);c.fill();}c.fillStyle='#ff704d';c.beginPath();c.arc(x,z,55,0,7);c.fill();c.restore();}
function frame(now:number){if(disposed)return;raf=requestAnimationFrame(frame);const dt=Math.min((now-last)/1000||.016,.04);last=now;const width=canvas.clientWidth,height=canvas.clientHeight;if(canvas.width!==Math.floor(width*renderer.getPixelRatio())||canvas.height!==Math.floor(height*renderer.getPixelRatio())){renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();}
if(mode==='countdown'){count-=dt;if(count<=0){count=0;mode='racing';}}
if(mode==='racing'){time+=dt;const gas=keys.w||keys.arrowup,brake=keys.s||keys.arrowdown,turn=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0);const wasDrifting=drifting;drifting=!!(keys[' ']&&turn&&speed>8);if(drifting)driftCharge=Math.min(2,driftCharge+dt);else if(wasDrifting){if(driftCharge>.6)boostTimer=1.1+driftCharge*.4;driftCharge=0;}const boosting=(keys.shift&&boost>0&&speed>2)||boostTimer>0;boostTimer=Math.max(0,boostTimer-dt);boost=Math.max(0,Math.min(100,boost+(keys.shift&&speed>2?-24:8)*dt));speed+=((gas?boosting?28:18:0)-(brake?32:3.8))*dt;speed=Math.max(brake?-8:0,Math.min(boosting?55:36,speed));angle+=turn*dt*(drifting?1.7:1.22)*Math.min(1,Math.abs(speed)/7)*(speed<0?-1:1);const travelAngle=angle-(drifting?turn*.22:0);x+=Math.cos(travelAngle)*speed*dt;z+=Math.sin(travelAngle)*speed*dt;const n=nearest(x,z);street=n.name||street;if(n.best>7.3&&Number.isFinite(n.best)){x=n.x+(x-n.x)*7.3/n.best;z=n.z+(z-n.z)*7.3/n.best;speed*=.95;}const next=at(checks[cp]);if(Math.hypot(x-next.x,z-next.z)<24){cp++;if(cp>=checks.length){mode='finished';cp=checks.length-1;speed=0;}}progress=cp===0?0:checks[cp-1];for(const r of rivals){r.s=Math.min(total,r.s+r.speed*dt);const p=at(r.s);if(Math.hypot(p.x-x,p.z-z)<2.5&&Math.abs(speed)>5){speed*=.8;x-=Math.sin(angle)*1.1;z+=Math.cos(angle)*1.1;}}padCooldown=Math.max(0,padCooldown-dt);if(padCooldown===0&&pads.some(p=>Math.hypot(p.position.x-x,p.position.z-z)<5)){boostTimer=1.8;padCooldown=2;}}
player.position.set(x,drifting?Math.sin(now/50)*.03:0,z);player.rotation.y=-angle;player.rotation.x=drifting?Math.sin(now/100)*.025:0;player.visible=!firstPerson;for(const r of rivals){const p=at(r.s);r.mesh.position.set(p.x,0,p.z);r.mesh.rotation.y=-p.a;}
const next=at(checks[Math.min(cp,checks.length-1)]);ring.position.set(next.x,5.8,next.z);ring.rotation.set(0,Math.PI/2-next.a,0);ring.material.opacity=.6+Math.sin(now/250)*.2;
const ready=mode==='ready';const behind=firstPerson?-.85:ready?10:8.5+Math.abs(speed)*.035;camPos.set(x-Math.cos(angle)*behind,firstPerson?1.8:ready?5.8:4.3,z-Math.sin(angle)*behind);camera.position.lerp(camPos,1-Math.exp(-dt*8));look.set(x+Math.cos(angle)*18,firstPerson?1.7:1.5,z+Math.sin(angle)*18);camera.lookAt(look);camera.fov=T.MathUtils.lerp(camera.fov,boostTimer>0||keys.shift?76:65,dt*3);camera.updateProjectionMatrix();renderer.render(scene,camera);
if(now-hudTime>100){hudTime=now;miniMap();update({mode,speed:Math.round(Math.abs(speed)*2.237),time,boost,progress:mode==='finished'?100:progress/total*100,street,position:mode==='finished'?1+rivals.filter(r=>r.s>=total).length:1+rivals.filter(r=>r.s>progress+25).length,count:Math.ceil(count),drift:drifting,camera:firstPerson?'Driver':'Chase'});}}
camera.position.set(x-Math.cos(angle)*10,5,z-Math.sin(angle)*10);raf=requestAnimationFrame(frame);
return {start:reset,pause,recover,toggleCamera,setKey,getState:()=>({mode,time,progress}),dispose:()=>{disposed=true;cancelAnimationFrame(raf);window.removeEventListener('keydown',handleDown);window.removeEventListener('keyup',handleUp);window.removeEventListener('blur',blur);scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});renderer.dispose();}};
}
