'use client';
import {useEffect,useRef,useState} from 'react';
import type {HUD,MapData} from './engine';
const fmt=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toFixed(2).padStart(5,'0')}`;
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),mini=useRef<HTMLCanvasElement>(null),engine=useRef<ReturnType<typeof import('./engine').makeGame>|null>(null);const [error,setError]=useState(''),[hud,setHud]=useState<HUD>({mode:'loading',speed:0,time:0,boost:100,progress:0,street:'South Park',position:4,count:3,drift:false,camera:'Chase'});
useEffect(()=>{let cancelled=false;const lifecycle=new AbortController();Promise.all([import('./engine'),fetch('/streets.json').then(r=>{if(!r.ok)throw Error('Could not load the street map. Please reload.');return r.json() as Promise<MapData>;})]).then(([module,data])=>{if(cancelled||!canvas.current||!mini.current)return;try{engine.current=module.makeGame(canvas.current,mini.current,data,setHud);}catch{setError('3D graphics could not start. Try a browser with WebGL enabled.');}
const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(context)try{context.registerTool({name:'start_race',description:'Start or restart the 3D SoMa kart race.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');if(!engine.current)throw Error('Game is not ready');engine.current.start();return engine.current.getState();}},{signal:lifecycle.signal});}catch{}}).catch(e=>setError(e.message));return()=>{cancelled=true;lifecycle.abort();engine.current?.dispose();};},[]);
const ready=hud.mode==='ready'||hud.mode==='loading';const press=(key:string,value:boolean)=>engine.current?.setKey(key,value);
return <main><header><a href="/" className="brand"><span className="brand-mark">SF</span> BAY CITY <em>KART</em></a><span className="district">SOMA + EMBARCADERO <i>01</i></span><button onClick={()=>engine.current?.pause()} disabled={ready}>{hud.mode==='paused'?'Resume ▶':'Pause Ⅱ'}</button></header><section className="arena"><canvas className="world" ref={canvas} aria-label="3D kart racing through real San Francisco streets. Arrow keys drive, Space drifts, Shift boosts, V changes camera."/><div className="vignette"/><div className="race-title"><span className="eyebrow">SAN FRANCISCO STREET SERIES</span><h2>South Park <span>→</span> the waterfront.</h2><p>{hud.street} <span> / </span> {hud.camera} camera</p></div>
{!ready&&<div className="place"><b>{hud.position}</b><span>/ 4<br/>POSITION</span></div>}
{(ready||hud.mode==='paused'||hud.mode==='finished'||error)&&<div className="start-card"><span className="sticker">{hud.mode==='finished'?'CHECKERED FLAG':hud.mode==='paused'?'PIT STOP':'REAL CITY. KART RULES.'}</span><h1>{hud.mode==='finished'?<>That’s a<br/>wrap!</>:hud.mode==='paused'?<>Taking<br/>a breather.</>:<>Small kart.<br/>Big city.</>}</h1><p>{error|| (hud.mode==='finished'?`Finished in ${fmt(hud.time)}. Ready for another shot at the waterfront?`:hud.mode==='paused'?'The race is paused. Your rivals can wait.':'Rip through South Park, drift around SoMa, and boost down the Embarcadero. Three rivals. One city loop.')}</p><div className="race-spec"><div><b>4.8 <small>KM</small></b><span>REAL STREET LOOP</span></div><div><b>4 <small>KARTS</small></b><span>ONE FINISH LINE</span></div></div><button className="go" disabled={hud.mode==='loading'||!!error} onClick={()=>hud.mode==='paused'?engine.current?.pause():engine.current?.start()}>{hud.mode==='loading'?'Building the city…':hud.mode==='paused'?'Back to the race →':hud.mode==='finished'?'Race again →':'Let’s race →'}</button><div className="start-help"><span>↑ / W &nbsp; ACCELERATE</span><span>← → / A D &nbsp; STEER</span><span>SPACE &nbsp; DRIFT</span><span>SHIFT &nbsp; BOOST</span></div></div>}
{hud.mode==='countdown'&&<div className="countdown" aria-live="assertive">{hud.count}</div>}{hud.drift&&<div className="drift-tag">DRIFT CHARGING <span>Release SPACE for a boost</span></div>}
<div className="minimap"><span>THE WATERFRONT LOOP <i>N ↑</i></span><canvas ref={mini} width={180} height={210} aria-label="Course minimap"/><div><i/> YOU <small>● RIVALS</small></div></div>
<div className="bottom-hud"><div className="speed"><b>{hud.speed.toString().padStart(2,'0')}</b><span>MPH</span></div><div className="timer"><span className="eyebrow">RACE TIME</span><b>{fmt(hud.time)}</b></div><div className="boost"><span className="eyebrow">BOOST <span>SHIFT</span></span><div role="meter" aria-label="Boost remaining" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(hud.boost)}><i style={{width:`${hud.boost}%`}}/></div></div></div><div className="right-controls"><button onClick={()=>engine.current?.toggleCamera()}>◉ Camera <kbd>V</kbd></button><button onClick={()=>engine.current?.recover()}>↻ Unstuck <kbd>R</kbd></button></div><div className="course-progress"><i style={{width:`${hud.progress}%`}}/></div><div className="touch">{[['←','arrowleft'],['↑','arrowup'],['↓','arrowdown'],['→','arrowright'],['DRIFT',' '],['BOOST','shift']].map(([label,key])=><button key={key} aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);press(key,true);}} onPointerUp={()=>press(key,false)} onPointerCancel={()=>press(key,false)}>{label}</button>)}</div></section><footer><span>REAL STREETS + BUILDING FOOTPRINTS · STYLIZED SCENERY & HEIGHTS</span><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors ↗</a><span>↑↓←→ DRIVE &nbsp; SPACE DRIFT &nbsp; SHIFT BOOST</span></footer></main>;
}
