'use client';
import {useEffect,useRef,useState} from 'react';
type P=number[];type Data={roads:{name:string;points:P[]}[];route:P[]};
const dist=(a:P,b:P)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
const fmt=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toFixed(2).padStart(5,'0')}`;
export default function Home(){
const canvas=useRef<HTMLCanvasElement>(null),keys=useRef<Record<string,boolean>>({}), game=useRef({mode:'ready',x:0,y:0,a:0,v:0,t:0,boost:100,cp:1,street:'Lombard Street',penalty:0}),data=useRef<Data|null>(null);
const [hud,setHud]=useState({mode:'loading',speed:0,time:0,boost:100,progress:0,street:'Russian Hill',distance:0}),[error,setError]=useState(false);
const start=()=>{const d=data.current;if(!d)return;const g=game.current;Object.assign(g,{mode:'racing',x:d.route[0][0],y:d.route[0][1],a:Math.atan2(d.route[1][1]-d.route[0][1],d.route[1][0]-d.route[0][0]),v:0,t:0,boost:100,cp:1});keys.current={};};
const pause=()=>{const g=game.current;if(g.mode==='racing')g.mode='paused';else if(g.mode==='paused')g.mode='racing';};
useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:'start_race',description:'Start or restart the San Francisco time trial.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');if(!data.current)throw Error('Street map is still loading');start();return {status:game.current.mode};}},{signal:lifecycle.signal});}catch{}return()=>lifecycle.abort();},[]);
useEffect(()=>{let dead=false,raf=0;fetch('/streets.json').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Data>}).then((d:Data)=>{if(dead)return;data.current=d;game.current.x=d.route[0][0];game.current.y=d.route[0][1];setHud(h=>({...h,mode:'ready'}));}).catch(()=>setError(true));
const down=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Shift'].includes(e.key))e.preventDefault();keys.current[e.key.toLowerCase()]=true;if(e.key==='Escape')pause();if(e.key.toLowerCase()==='r')start();};const up=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false;};const blur=()=>{keys.current={};if(game.current.mode==='racing')game.current.mode='paused';};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
let last=0,tick=0;let cam:P=[0,0];
function frame(now:number){raf=requestAnimationFrame(frame);const dt=Math.min((now-last)/1000||0,.035);last=now;const c=canvas.current,d=data.current;if(!c||!d)return;const ctx=c.getContext('2d');if(!ctx)return;const g=game.current,k=keys.current;const w=c.clientWidth,h=c.clientHeight,ratio=Math.min(devicePixelRatio,2);if(c.width!==w*ratio||c.height!==h*ratio){c.width=w*ratio;c.height=h*ratio;}ctx.setTransform(ratio,0,0,ratio,0,0);
const nearest=(p:P)=>{let best=1e9,point=p,name='';for(const road of d!.roads)for(let i=1;i<road.points.length;i++){const a=road.points[i-1],b=road.points[i],vx=b[0]-a[0],vy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*vx+(p[1]-a[1])*vy)/(vx*vx+vy*vy||1))),q=[a[0]+vx*t,a[1]+vy*t],dd=dist(p,q);if(dd<best){best=dd;point=q;name=road.name;}}return {best,point,name};};
if(g.mode==='racing'){g.t+=dt;const boost=(k.shift||k.b)&&g.boost>0&&g.v>4;const gas=k.arrowup||k.w;const brake=k.arrowdown||k.s||k[' '];g.v+=((gas?(boost?38:25):0)-(brake?52:6))*dt;g.v=Math.max(0,Math.min(boost?64:43,g.v));g.boost=Math.max(0,Math.min(100,g.boost+(boost?-27:10)*dt));const steer=(k.arrowright||k.d?1:0)-(k.arrowleft||k.a?1:0);g.a+=steer*dt*2.3*Math.min(1,g.v/9);g.x+=Math.cos(g.a)*g.v*dt;g.y+=Math.sin(g.a)*g.v*dt;const n=nearest([g.x,g.y]);g.street=n.name||'San Francisco';if(n.best>12){g.x=n.point[0]+(g.x-n.point[0])*12/n.best;g.y=n.point[1]+(g.y-n.point[1])*12/n.best;g.v*=.94;}while(g.cp<d.route.length&&dist([g.x,g.y],d.route[g.cp])<24)g.cp++;if(g.cp>=d.route.length){g.mode='finished';g.v=0;}}
const overview=g.mode==='ready';const zoom=overview?Math.min(w/2400,h/1800):Math.min(2.4,Math.max(1.4,w/650));const target=overview?[650,200]:[g.x+Math.cos(g.a)*55,g.y+Math.sin(g.a)*55];if(overview||!last)cam=target;else cam=[cam[0]+(target[0]-cam[0])*.12,cam[1]+(target[1]-cam[1])*.12];ctx.fillStyle='#101a23';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(zoom,zoom);ctx.translate(-cam[0],-cam[1]);
// Real geographic street geometry forms both the map and collision surface.
function line(points:P[],color:string,width:number){if(!ctx)return;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();}
for(const r of d.roads)line(r.points,'#293642',27);for(const r of d.roads)line(r.points,'#18232d',22);for(const r of d.roads)line(r.points,'#34424c',.65);
line(d.route,'#9cf9a91c',35);line(d.route,'#a6f78b',overview?4:2.5);ctx.setLineDash([5,12]);line(d.route,'#defed0',1);ctx.setLineDash([]);
const seen=new Set();ctx.font=`${11/Math.min(zoom,1.5)}px Arial`;ctx.fillStyle='#82929f';ctx.textAlign='center';for(const r of d.roads){if(!r.name||seen.has(r.name))continue;const a=r.points[0],b=r.points[r.points.length-1];if(dist(a,b)<70)continue;const p=[(a[0]+b[0])/2,(a[1]+b[1])/2];if(Math.abs(p[0]-cam[0])*zoom>w/2||Math.abs(p[1]-cam[1])*zoom>h/2)continue;seen.add(r.name);ctx.save();ctx.translate(p[0],p[1]);let angle=Math.atan2(b[1]-a[1],b[0]-a[0]);if(angle>Math.PI/2||angle<-Math.PI/2)angle+=Math.PI;ctx.rotate(angle);ctx.fillText(r.name,0,-20);ctx.restore();}
const cp=d.route[Math.min(g.cp,d.route.length-1)];ctx.beginPath();ctx.arc(cp[0],cp[1],18+Math.sin(now/240)*2,0,Math.PI*2);ctx.strokeStyle='#c3ff6d';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#b5ff7522';ctx.fill();
ctx.save();ctx.translate(g.x,g.y);ctx.rotate(g.a);ctx.shadowColor='#ff7353';ctx.shadowBlur=15;ctx.fillStyle='#ff7755';ctx.fillRect(-9,-4.5,18,9);ctx.shadowBlur=0;ctx.fillStyle='#17212b';ctx.fillRect(1,-3.5,4,7);ctx.fillStyle='#ffeab4';ctx.fillRect(7,-4,2,2);ctx.fillRect(7,2,2,2);ctx.restore();ctx.restore();
// Always-visible course overview while driving.
if(!overview&&w>700){ctx.save();ctx.translate(w-186,h-160);ctx.fillStyle='#0b121be8';ctx.fillRect(-14,-14,176,146);ctx.translate(12,10);ctx.scale(.056,.056);ctx.translate(200,200);for(const r of d.roads)line(r.points,'#3d4b55',7);line(d.route,'#b3fb85',22);ctx.fillStyle='#ff7755';ctx.beginPath();ctx.arc(g.x,g.y,65,0,7);ctx.fill();ctx.restore();}
if(now-tick>90){tick=now;setHud({mode:g.mode,speed:Math.round(g.v*2.237),time:g.t,boost:g.boost,progress:Math.min(100,(g.cp-1)/(d.route.length-1)*100),street:g.street,distance:Math.round(dist([g.x,g.y],cp))});}}
raf=requestAnimationFrame(frame);return()=>{dead=true;cancelAnimationFrame(raf);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[]);
return <main><header><a className="brand" href="/">SF<span> / </span>MIDNIGHT RUN<span className="edition">VOL. 01</span></a><div className="live"><i/> SAN FRANCISCO, CA</div><button onClick={pause} disabled={!['racing','paused'].includes(hud.mode)}>{hud.mode==='paused'?'Resume ↗':'Pause Ⅱ'}</button></header><section className="arena"><canvas ref={canvas} aria-label="San Francisco racing map. Use arrow keys or WASD to drive, Shift to boost, and Escape to pause."/><div className="topline"><span>37.8021° N &nbsp; 122.4187° W</span><span>REAL STREETS. &nbsp; AFTER HOURS.</span></div><div className="location"><span className="eyebrow">{hud.mode==='ready'?'TONIGHT’S CIRCUIT':'ON THE STREETS'}</span><h2>{hud.mode==='ready'?'The Northside Loop':hud.street}</h2><p>{hud.mode==='ready'?'Russian Hill → North Beach → Nob Hill':`${Math.round(hud.progress)}% complete · Next marker ${hud.distance} m`}</p></div>
{['ready','loading','finished','paused'].includes(hud.mode)&&<div className="start-card"><span className="eyebrow">{hud.mode==='finished'?'FINISH LINE':hud.mode==='paused'?'TAKE A BREATHER':'SAN FRANCISCO / TIME TRIAL'}</span><h1>{hud.mode==='finished'?'Run complete.':hud.mode==='paused'?'Night on hold.':<>Own the<br/>night shift.</>}</h1><p>{hud.mode==='finished'?`Your time: ${fmt(hud.time)}. Take another run and beat it.`:hud.mode==='paused'?'Your clock is paused. Pick up where you left off.':'Trace the lime route through the city’s real streets. Keep it tight at the corners. Make every second count.'}</p><div className="race-spec"><div><b>4.7<span> KM</span></b><small>STREET CIRCUIT</small></div><div><b>01<span> DRIVER</span></b><small>AGAINST THE CLOCK</small></div></div><button className="go" disabled={hud.mode==='loading'||error} onClick={hud.mode==='paused'?pause:start}>{error?'Map unavailable — reload':hud.mode==='loading'?'Loading street map…':hud.mode==='paused'?'Resume run ↗':hud.mode==='finished'?'Race again ↗':'Start your run ↗'}</button><small className="hint">ARROW KEYS / WASD TO DRIVE · SHIFT TO BOOST</small></div>}
<div className="bottom-hud"><div className="speed"><b>{hud.speed.toString().padStart(3,'0')}</b><span>MPH</span></div><div className="timer"><span className="eyebrow">RUN TIME</span><b>{fmt(hud.time)}</b></div><div className="boost"><span className="eyebrow">BOOST <span>SHIFT</span></span><div><i style={{width:`${hud.boost}%`}}/></div></div><button className="reset" onClick={start} disabled={hud.mode==='loading'}>↻ Restart <kbd>R</kbd></button></div><div className="touch">{[['←','arrowleft'],['↑','arrowup'],['↓','arrowdown'],['→','arrowright'],['BOOST','shift']].map(([label,key])=><button key={key} aria-label={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);keys.current[key]=true;}} onPointerUp={()=>keys.current[key]=false} onPointerCancel={()=>keys.current[key]=false}>{label}</button>)}</div></section><footer><span><i/> CLOSED-COURSE ARCADE · REAL MAP, STYLIZED WORLD</span><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors ↗</a><span>WASD / ↑↓←→ &nbsp; DRIVE &nbsp; · &nbsp; SPACE &nbsp; BRAKE</span></footer></main>;
}
