// Affectionate cartoon interpretations; clothes and silhouettes distinguish the racers.
export const HUMAN_STYLES = {
  daniel: {
    suit: '#263e62',
    skin: '#e7af8a',
    hair: '#514942',
    gray: true,
    glasses: false,
    beard: false,
    tie: true,
    curls: false,
  },
  sam: {
    suit: '#172e46',
    skin: '#e1ac8d',
    hair: '#493e34',
    gray: false,
    glasses: false,
    beard: false,
    tie: true,
    curls: false,
  },
  dario: {
    suit: '#263348',
    skin: '#dca27e',
    hair: '#35251e',
    gray: false,
    glasses: true,
    beard: true,
    tie: false,
    curls: true,
  },
  elon: {
    suit: '#22252b',
    skin: '#edc1aa',
    hair: '#533e31',
    gray: false,
    glasses: false,
    beard: false,
    tie: false,
    curls: false,
  },
  mark: {
    suit: '#85898b',
    skin: '#efc5b0',
    hair: '#845c3e',
    gray: false,
    glasses: false,
    beard: false,
    tie: false,
    curls: true,
  },
  garry: {
    suit: '#282e35',
    skin: '#d6a77f',
    hair: '#252425',
    gray: false,
    glasses: true,
    beard: false,
    tie: false,
    curls: false,
  },
  pejman: {
    suit: '#37658d',
    skin: '#d6a079',
    hair: '#49443c',
    gray: true,
    glasses: false,
    beard: false,
    tie: false,
    curls: false,
  },
  andrew: {
    suit: '#30303f',
    skin: '#d8ab85',
    hair: '#202225',
    gray: false,
    glasses: true,
    beard: false,
    tie: false,
    curls: false,
  },
  aditya: {
    suit: '#d9dbda',
    skin: '#c58f63',
    hair: '#171c19',
    gray: false,
    glasses: false,
    beard: false,
    tie: false,
    curls: false,
  },
};
